# Generated by Django 4.1.5 on 2023-01-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_column='Group name', max_length=80, verbose_name='Group name')),
                ('group_start_date', models.DateField(default='2022-12-06')),
                ('group_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
